version: '2'
services:

  webtrees:
    image:  lomadi/webtrees:latest
    container_name:  webtrees
    links:
      - webtrees-database:webtrees-database
    ports:
      - "10080:80"
    depends_on:
      - webtrees-database
      - webtrees-data-volumes
    volumes_from: 
      - webtrees-data-volumes
       
  webtrees-database:
    image: mysql:5.6
    container_name: webtrees-database
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=mustnotchange
      - MYSQL_DATABASE=webtrees
      - MYSQL_USER=webtrees
      - MYSQL_PASSWORD=mustnotchange
    volumes:
       - ./default-data:/docker-entrypoint-initdb.d
    volumes_from: 
      - webtrees-data-volumes
    depends_on:
      - webtrees-data-volumes

  webtrees-data-volumes:
    image: busybox
    container_name: webtrees-data-volumes
    volumes:
      - /Users/mue/dockerdata/webtrees/var/lib/mysql:/var/lib/mysql
      - /Users/mue/dockerdata/webtrees/var/www/html/webtrees/data:/var/www/html/webtrees/data
      

# default user
# admin / changethepassword
