# WEBTREES DOCKER COMPOSE
#
# start   http://localhost:§§PORT
# default user: admin / changethepassword
#

version: '2'
services:

  webtrees:
    image:  lomadi/webtrees:latest
    container_name:  webtrees
    links:
      - webtrees-database:webtrees-database
    ports:
      - "§§PORT:80"
    depends_on:
      - webtrees-database
      - webtrees-data-volumes
    volumes_from: 
      - webtrees-data-volumes
       
  webtrees-database:
    build: 
        context: ./images/database
    image: lomadi/webtrees-database
    container_name:   webtrees-database
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=mustnotchange
      - MYSQL_DATABASE=webtrees
      - MYSQL_USER=webtrees
      - MYSQL_PASSWORD=mustnotchange
    volumes_from: 
      - webtrees-data-volumes
    depends_on:
      - webtrees-data-volumes

  webtrees-data-volumes:
    image: busybox
    container_name: webtrees-data-volumes
    volumes:
      - §§FOLDER/webtrees/var/lib/mysql:/var/lib/mysql
      - §§FOLDER/webtrees/var/www/html/webtrees/data:/var/www/html/webtrees/data
      